# Uncomment this line to define a global platform for your project
platform :ios, '15.0'
# Uncomment this line if you're using Swift
use_frameworks!

target '70K Bands' do
	pod 'Firebase/Core', '~> 8.15.0'
	pod 'Firebase/Messaging', '~> 8.15.0'
	pod 'Firebase/Database', '~> 8.15.0'
        pod 'AWSSNS', '~> 2.3.0'
        pod 'Bolts'
end

target '70K BandsTests' do
        pod 'Firebase/Core', '~> 8.15.0'
        pod 'Firebase/Messaging', '~> 8.15.0'
	pod 'Firebase/Database', '~> 8.15.0'
        pod 'AWSSNS', '~> 2.3.0'
        pod 'Bolts'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
               end
          end
   end
end
