# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Firebase/Core','~> 5.20.0'
pod 'Firebase/Messaging','~> 5.20.0'
pod 'Firebase/Database','~> 5.20.0'

target '70K Bands' do
	pod 'Firebase/Core','~> 5.20.0'
	pod 'Firebase/Messaging','~> 5.20.0'
	pod 'Firebase/Database','~> 5.20.0'
end

target '70K BandsTests' do
        pod 'Firebase/Core','~> 5.20.0'
        pod 'Firebase/Messaging','~> 5.20.0'
	pod 'Firebase/Database','~> 5.20.0'
end

