# Uncomment this line to define a global platform for your project
platform :ios, '13.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Database'

target '70K Bands' do
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'Firebase/Database'
end

target '70K BandsTests' do
        pod 'Firebase/Core'
        pod 'Firebase/Messaging'
	pod 'Firebase/Database'
end

