source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
pod 'AWSSNS'
pod 'Bolts'

link_with '70K Bands', '70K BandTests'

target '70K Bands' do
	platform :ios, '8.0'
#	pod 'AWSMobileAnalytics', '~> 2.3.0'
	pod 'AWSSNS', '~> 2.3.0’
end

target '70K BandsTests' do
        platform :ios, '8.0'
#        pod 'AWSMobileAnalytics', '~> 2.3.0'
        pod 'AWSSNS', '~> 2.3.0’
end
