source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target '70K Bands' do
	use_frameworks!
	pod 'Bolts'
	pod 'SQLite.swift', '~> 0.15.3'
end

target '70K BandsTests' do
	use_frameworks!
	pod 'SQLite.swift', '~> 0.15.3'
end
